In [14]:
import numpy as np
arr1=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
print("Original array:\n",arr1)

Original array:
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [15]:
#returnss every other rows
print("\nEvery other rows: \n",arr[0:3:2])


Every other rows: 
 [1 3]


In [16]:
#Return every other element from the entire array
arr=np.array([1,2,3,4,5,6,7])
print("\nOriginal array:",arr)
print("\nReturns every other elements in the array:arr[::2]:",arr[::2])


Original array: [1 2 3 4 5 6 7]

Returns every other elements in the array:arr[::2]: [1 3 5 7]


In [17]:
#Slicing array 
temp =arr1[:2,:3]
print("\nArray with first 2 rows and 3 columns:\n",temp)


Array with first 2 rows and 3 columns:
 [[-1.   2.   0. ]
 [ 4.  -0.5  6. ]]


In [17]:
#Integer array indexing
import numpy as np
arr=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,7,4,2.0]])
temp=arr[[0,1,2,3],[3,2,1,0]]
print("\nElements at indices(0,3),(1,2),(2,1)," "(3,0):\n",temp)


Elements at indices(0,3),(1,2),(2,1),(3,0):
 [4. 6. 0. 3.]


In [19]:
#boolean array indexing
cond=arr>2
#cond is a boolean array
temp=arr[cond]
print("\nElements greater than 2:\n",temp)


Elements greater than 2:
 [4.  4.  6.  2.6 7.  8.  3.  7.  4. ]


In [21]:
#joining two array
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print("\nOriginal arrays:\n",arr1,arr2)
print("\nJoined array:\n",arr)


Original arrays:
 [1 2 3] [4 5 6]

Joined array:
 [1 2 3 4 5 6]


In [22]:
#Horizontal join
arr=np.hstack((arr1,arr2))
print("\nHorizontal joining:\n",arr)


Horizontal joining:
 [1 2 3 4 5 6]


In [24]:
#Vertical join
arr=np.vstack((arr1,arr2))
print("\nVertical joining:\n",arr)


Vertical joining:
 [[1 2 3]
 [4 5 6]]


In [25]:
#Depth join
arr=np.dstack((arr1,arr2))
print("\nDepth joining:\n",arr)


Depth joining:
 [[[1 4]
  [2 5]
  [3 6]]]


In [27]:
#Splitting array
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print("\nOriginal array:\n",arr)
print("\nSplitted array:\n",newarr)
#Displaying splitting array in another form:\n")
print(newarr[0])
print(newarr[1])
print(newarr[2])


Original array:
 [1 2 3 4 5 6]

Splitted array:
 [array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]
