In [3]:
import numpy as np
a = np.array([[1, 2, 4], [5, 8, 7]])
print ("Array created using passed list:\n", a)

Array created using passed list:
 [[1 2 4]
 [5 8 7]]


In [4]:
# Creating a 3X4 array with all zeros
b = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", b)


An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
#Create a constant value array of complex type
c = np.full((3, 3), 6)
print ("\nAn array initialized with all 6s.\n", c)


An array initialized with all 6s.
 [[6 6 6]
 [6 6 6]
 [6 6 6]]
